In [1]:
import numpy as np
import keras
import tensorflow as tf


In [2]:
X_train = np.array([[1.0], [2.0]], dtype=np.float32)           
Y_train = np.array([[300.0], [500.0]], dtype=np.float32) 

In [3]:
linear_layer = tf.keras.layers.Dense(units=1, activation = 'linear', )

In [4]:
linear_layer.get_weights()

[]

In [6]:
a1 = linear_layer(X_train[0].reshape(1,1))
print(a1)

tf.Tensor([[-0.81914157]], shape=(1, 1), dtype=float32)


In [7]:
w, b= linear_layer.get_weights()
print(w,b)

[[-0.81914157]] [0.]


In [10]:
set_w = np.array([[300]])
set_b = np.array([100])


linear_layer.set_weights([set_w, set_b])
print(linear_layer.get_weights())

[array([[300.]], dtype=float32), array([100.], dtype=float32)]


In [12]:
a1 = linear_layer(X_train[0].reshape(1,1))
print(a1)
alin = np.dot(set_w,X_train[0].reshape(1,1)) + set_b
print(alin)

tf.Tensor([[400.]], shape=(1, 1), dtype=float32)
[[400.]]


In [13]:
prediction_tf = linear_layer(X_train)
prediction_np = np.dot( X_train, set_w) + set_b

In [14]:
print(prediction_np,prediction_tf)

[[400.]
 [700.]] tf.Tensor(
[[400.]
 [700.]], shape=(2, 1), dtype=float32)
